[package]
name = "rust-atomics-locks"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
rand = "0.8.3"
scraper = "0.20.0"
tokio = { version = "1.40.0", features = ["full"] }  # Include tokio for async
bytes = "1.8.0"